version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: fes_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: servicio_social
      MYSQL_USER: fes_user
      MYSQL_PASSWORD: fes_pass
    ports:
      - "3306:3306"

    volumes:
      
      - ./mysql-init:/docker-entrypoint-initdb.d

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 10
    


